//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PY1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Delevery
    {
        public int ID_Delevery { get; set; }
        public int Genres_ID { get; set; }
        public int Comicses_ID { get; set; }
        public System.DateTime DateZakaza { get; set; }
    
        public virtual Comicses Comicses { get; set; }
        public virtual Genres Genres { get; set; }
    }
}
